import Footer from '@components/layout/Footer';
import Header from '@components/layout/Header';
import TailwindCSS from '@components/layout/TailwindCSS';

import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';

import './globals.css';

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ko">
            <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
                <TailwindCSS />
                <Header className="mx-auto h-[130px] w-full max-w-screen-xl flex-1 px-5" />
                <main className="mx-auto w-full max-w-screen-xl flex-1 px-5">{children}</main>
                <Footer />
            </body>
        </html>
    );
}
