# 1) build stage
FROM node:18-alpine AS builder
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .
RUN npm run build

# 2) production stage
FROM node:18-alpine
WORKDIR /app

# production 의존만 설치
COPY package.json package-lock.json ./
RUN npm ci --omit=dev

# 빌드된 JS 복사
COPY --from=builder /app/dist ./dist

ENV NODE_ENV=production
EXPOSE 4000

CMD ["node", "dist/main"]